<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="2575.3">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px}
  </style>
</head>
<body>
<p class="p1">[build]</p>
<p class="p1"><span class="Apple-converted-space">  </span>publish = "."</p>
<p class="p1"><span class="Apple-converted-space">  </span>command = ""</p>
<p class="p2"><span class="Apple-converted-space">  </span></p>
<p class="p1">[[headers]]</p>
<p class="p1"><span class="Apple-converted-space">  </span>for = "/*"</p>
<p class="p1"><span class="Apple-converted-space">  </span>[headers.values]</p>
<p class="p1"><span class="Apple-converted-space">    </span>Content-Type = "text/html; charset=UTF-8"</p>
</body>
</html>
